import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/sass/app.scss',
                'resources/js/app.js',
                'resources/js/albaranes-form.js',
                'resources/js/bootstrap.js',
                
                // --- Archivos CSS de las vistas (Ordenados alfabéticamente) ---
                'resources/css/albaran-pdf-viewer.css',
                'resources/css/albaranes-clientes-index.css',
                'resources/css/albaranes-edit.css',
                'resources/css/albaranes-form.css',
                'resources/css/almacenes-create.css',
                'resources/css/app.css',
                'resources/css/clases-create.css',
                'resources/css/clases-index.css',
                'resources/css/clientes-create.css',
                'resources/css/clientes-edit.css',
                'resources/css/clientes-index.css',
                'resources/css/clientes-show.css',
                'resources/css/correlativos.css',
                'resources/css/document-states.css',
                'resources/css/documentos-create.css',
                'resources/css/documentos-index.css',
                'resources/css/edit_profile.css',
                'resources/css/gestion-proyectos.css',
                'resources/css/inventario-acciones.css',
                'resources/css/inventario-create.css',
                'resources/css/inventario-index.css',
                'resources/css/inventario-item-create.css',
                'resources/css/inventario-salida.css',
                'resources/css/inventario-traslado.css',
                'resources/css/login.css',
                'resources/css/pedidos-clientes-create.css',
                'resources/css/pedidos-clientes-index.css',
                'resources/css/pedidos-show-cliente.css',
                'resources/css/personal-index.css',
                'resources/css/personal-show.css',
                'resources/css/presupuestos-create.css',
                'resources/css/presupuestos-detail.css',
                'resources/css/presupuestos-index.css',
                'resources/css/presupuestos-show.css',
                'resources/css/proyecto-create.css',
                'resources/css/proyecto-edit.css',
                'resources/css/proyecto-show.css',
                'resources/css/register.css',
                'resources/css/reset-password.css',
                'resources/css/show_profile.css',
                'resources/css/usuarios-create.css',
                'resources/css/usuarios-edit.css',
                'resources/css/usuarios-panel.css',
                'resources/css/usuarios-show.css',
            ],
            refresh: true,
        }),
    ],
});